### ISSUE TITLE
Can't spawn after Startup

### ISSUE THREAD

**Issue by tliron** [IyesGames/iyes_perf_ui#14]
Maybe I just misunderstand something basic about Bevy UI. :)

I wanted a key to toggle the UI, but I get this error:

```
2024-04-03T02:39:37.117705Z  WARN bevy_ui::layout: Unstyled child in a UI entity hierarchy. You are using an entity without UI components as a child of an entity with UI components, results may be unexpected.
thread 'Compute Task Pool (22)' panicked at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ui-0.13.1/src/layout/mod.rs:132:60:
called `Option::unwrap()` on a `None` value
```

My code:

```rust
impl Plugin for MyPlugin {
    fn build(&self, app: &mut App) {
        app.init_state::<Mode>()
            .add_plugins((
                FrameTimeDiagnosticsPlugin,
                EntityCountDiagnosticsPlugin,
                SystemInformationDiagnosticsPlugin,
                PerfUiPlugin,
            ))
            .add_systems(Update, handle_input);
    }
}

fn handle_input(
    mut commands: Commands,
    input: Res<ButtonInput<KeyCode>>,
    perfs: Query<Entity, With<PerfUiRoot>>,
) {
    if input.just_pressed(KeyCode::F1) {
        match perfs.get_single() {
            Ok(perf) => {
                println!("remove perf!");
                commands.entity(perf).despawn_recursive();
            }
            Err(_) => {
                println!("perf!");
                commands.spawn(PerfUiCompleteBundle::default());
            }
        }
    }
}
```

**Comment by inodentry** [comment]
The issue is that the Bundle (or individual entry components) you add to the newly spawned entity needs to be processed by `iyes_perf_ui` to create the actual Bevy UI hierarchy. `iyes_perf_ui` systems also run in `Update`. Without any ordering dependencies, you get a race, and you are left with a broken UI hierarchy.

The fix for your code is to add `.before(iyes_perf_ui::PerfUiSet::Setup)` to your system.

I have now added a `toggle` example to the repo to show it working.

It's not ideal, I know. I will have to think about how to avoid this footgun. Perhaps I could put `iyes_perf_ui`'s systems in `PostUpdate` instead, but then I would have to be careful to order them around Bevy's internals.

**Comment by tliron** [comment]
Thanks for the response! I did assume a workaround could look something like that.

I think the issue is that your current design has a very "reactive" initialization. The entire logic is in the `Update` schedule, where you check if things are already initialized and there is no `Setup` function. The system function itself is named `setup_perf_ui_entry`, which implies a different schedule in my mind. I wonder if the setup vs. the update logic can be separated? Perhaps the "global" state of the plugin can live in a resource?

Sorry if my suggestions sound naïve, I'm still new to Bevy. :)
